
async function fetchJson(path, fallback = {body: []}) {
  try { const response = await fetch(path, {cache: 'no-store'}); if (!response.ok) throw new Error(path); return await response.json(); }
  catch (error) { return fallback; }
}
function getItems(data) { return Array.isArray(data) ? data : (data.body || []); }
let allProjects=[], currentProjectIndex=0, currentPhotoIndex=0, currentPhotos=[], lightboxZoom=1;
function isRecent(dateValue){ if(!dateValue)return false; const d=new Date(dateValue); return !Number.isNaN(d.getTime()) && (Date.now()-d.getTime())/86400000<=30; }
function projectCard(r,index){ return `<article class="gallery-item" data-index="${index}" data-cat="${r.category}" data-search="${(r.title+' '+r.description+' '+(r.details||'')).toLowerCase()}" title="Cliquer pour ouvrir l'image"><img src="${r.image}" alt="${r.title}"><div>${r.featured?'<span class="star">À la une</span>':''}${isRecent(r.date)?'<span class="star">Nouveau</span>':''}<strong>${r.icon||''} ${r.title}</strong><small>${r.description||''}</small>${r.details?`<em>${r.details}</em>`:''}</div></article>`; }
function normalizePhotos(p){ return [{photo:p.image,caption:'Image principale'}].concat((p.photos||[]).map(ph=>typeof ph==="string"?{photo:ph,caption:""}:ph)).filter(ph=>ph.photo); }
function prepareProject(index){ currentProjectIndex=index; currentPhotos=normalizePhotos(allProjects[index]); currentPhotoIndex=0; }
function setupFilters(){ const apply=()=>{ const f=document.querySelector('.filter-btn.active')?.dataset.filter||'all'; const q=(document.getElementById('gallerySearch')?.value||'').toLowerCase().trim(); document.querySelectorAll('.gallery-item').forEach(i=>{ const okCat=f==='all'||i.dataset.cat===f; const okText=!q||i.dataset.search.includes(q); i.style.display=(okCat&&okText)?'block':'none'; }); }; document.querySelectorAll('.filter-btn').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');apply();})); document.getElementById('gallerySearch')?.addEventListener('input',apply); }
function ensureLightbox(){ let lb=document.getElementById('lightbox'); if(lb)return lb; lb=document.createElement('div'); lb.className='lightbox'; lb.id='lightbox'; lb.innerHTML=`<button class="lightbox-close" onclick="closeLightbox()">×</button><button class="lightbox-prev" onclick="prevLightbox()">‹</button><img id="lightboxImage" src="" alt=""><button class="lightbox-next" onclick="nextLightbox()">›</button><button class="lightbox-zoom" onclick="toggleLightboxZoom()">Zoom</button><div class="lightbox-caption" id="lightboxCaption"></div>`; document.body.appendChild(lb); setupLightboxEvents(); return lb; }
function openLightbox(){ if(!currentPhotos.length)return; const lb=ensureLightbox(); const img=document.getElementById('lightboxImage'); const cap=document.getElementById('lightboxCaption'); const ph=currentPhotos[currentPhotoIndex]; img.src=ph.photo; img.alt=ph.caption||''; cap.textContent=ph.caption||allProjects[currentProjectIndex]?.title||''; lightboxZoom=1; img.style.transform='scale(1)'; lb.classList.add('open'); }
function closeLightbox(){ document.getElementById('lightbox')?.classList.remove('open'); }
function setLightboxPhoto(index){ if(!currentPhotos.length)return; currentPhotoIndex=(index+currentPhotos.length)%currentPhotos.length; openLightbox(); }
function prevLightbox(){ setLightboxPhoto(currentPhotoIndex-1); } function nextLightbox(){ setLightboxPhoto(currentPhotoIndex+1); }
function toggleLightboxZoom(){ const img=document.getElementById('lightboxImage'); if(!img)return; lightboxZoom=lightboxZoom===1?2:1; img.style.transform=`scale(${lightboxZoom})`; }
function setupLightboxEvents(){ const lb=document.getElementById('lightbox'); const img=document.getElementById('lightboxImage'); lb?.addEventListener('click',e=>{if(e.target.id==='lightbox')closeLightbox();}); img?.addEventListener('dblclick',toggleLightboxZoom); img?.addEventListener('wheel',e=>{e.preventDefault();lightboxZoom+=e.deltaY<0?.15:-.15;lightboxZoom=Math.max(1,Math.min(3,lightboxZoom));img.style.transform=`scale(${lightboxZoom})`;},{passive:false}); let startX=null; lb?.addEventListener('touchstart',e=>startX=e.touches[0].clientX,{passive:true}); lb?.addEventListener('touchend',e=>{if(startX===null)return; const dx=e.changedTouches[0].clientX-startX; if(Math.abs(dx)>50)dx>0?prevLightbox():nextLightbox(); startX=null;},{passive:true}); }
function setupKeyboard(){ document.addEventListener('keydown',e=>{const open=document.getElementById('lightbox')?.classList.contains('open'); if(e.key==='Escape'&&open)closeLightbox(); if(e.key==='ArrowLeft'&&open)prevLightbox(); if(e.key==='ArrowRight'&&open)nextLightbox();}); }
async function renderGallery(){ const grid=document.getElementById('galleryGrid'); if(!grid)return; allProjects=getItems(await fetchJson('/content/realisations.json')).filter(r=>!r.draft); allProjects.sort((a,b)=>new Date(b.date||0)-new Date(a.date||0)); grid.innerHTML=allProjects.map(projectCard).join(''); setupFilters(); grid.addEventListener('click',e=>{const card=e.target.closest('.gallery-item'); if(!card)return; prepareProject(Number(card.dataset.index)); openLightbox();}); setupKeyboard(); }
async function renderFeatured(){ const grid=document.getElementById('featuredGrid'); if(!grid)return; const data=getItems(await fetchJson('/content/realisations.json')).filter(r=>!r.draft&&r.featured).slice(0,3); grid.innerHTML=data.map((r,i)=>projectCard(r,i)).join(''); grid.addEventListener('click',e=>{const card=e.target.closest('.gallery-item'); if(!card)return; allProjects=data; prepareProject(Number(card.dataset.index)); openLightbox();}); setupKeyboard(); }
async function renderAvis(){ const grid=document.getElementById('avisGrid'); if(!grid)return; const data=getItems(await fetchJson('/content/avis.json')); grid.innerHTML=data.map(a=>`<article class="card"><h3>${'⭐'.repeat(Number(a.rating)||5)}<br>${a.name}</h3><p>${a.text}</p></article>`).join(''); }
async function renderActualites(){ const grid=document.getElementById('actualitesGrid'); if(!grid)return; const data=getItems(await fetchJson('/content/actualites.json')); grid.innerHTML=data.map(p=>`<article class="card"><h3>${p.title}</h3><p><strong>${(p.date||'').slice(0,10)}</strong></p><p>${p.excerpt}</p></article>`).join(''); }
document.addEventListener('DOMContentLoaded',()=>{renderGallery();renderFeatured();renderAvis();renderActualites();});
