
let data={body:[]}, selected=-1, selectedLibraryImage="", currentListFilter="active";
const $=id=>document.getElementById(id);
const $$=sel=>[...document.querySelectorAll(sel)];
const CATEGORY_ICONS={reparations:"🔧",impression3d:"🖨️",laser:"🔥",decoupe:"✂️",creations:"🎨"};
const CATEGORY_LABELS={reparations:"Réparations",impression3d:"Impression 3D",laser:"Gravure laser",decoupe:"Découpe laser",creations:"Créations"};
const categoryIcon=c=>CATEGORY_ICONS[c]||"🎨";
const categoryLabel=c=>CATEGORY_LABELS[c]||c||"";

function on(id,event,fn){const el=$(id); if(el) el.addEventListener(event,fn);}
function showView(id){$$(".tab").forEach(x=>x.classList.remove("active"));$$(".view").forEach(x=>x.classList.remove("active"));document.querySelectorAll(`[data-open="${id}"]`).forEach(x=>x.classList.add("active"));if($(id))$(id).classList.add("active");}
function esc(s){return String(s).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));}
function settings(){return{owner:localStorage.getItem("gh_owner")||"LuckyMcGyver",repo:localStorage.getItem("gh_repo")||"lucky-reparations-creations",branch:localStorage.getItem("gh_branch")||"main",token:localStorage.getItem("gh_token")||""};}
function updateStatus(){const st=$("status"); if(!st)return; if(settings().token){st.textContent="Connecté à GitHub";st.classList.add("ok");}else{st.textContent="Non connecté à GitHub";st.classList.remove("ok");}}
function loadSettings(){const s=settings(); if($("repoOwner"))$("repoOwner").value=s.owner; if($("repoName"))$("repoName").value=s.repo; if($("repoBranch"))$("repoBranch").value=s.branch; if($("githubToken"))$("githubToken").value=s.token; updateStatus();}
function saveSettings(){localStorage.setItem("gh_owner",$("repoOwner").value.trim());localStorage.setItem("gh_repo",$("repoName").value.trim());localStorage.setItem("gh_branch",$("repoBranch").value.trim());localStorage.setItem("gh_token",$("githubToken").value.trim());updateStatus();alert("Paramètres enregistrés.");}
async function gh(path,options={}){const s=settings();if(!s.token)throw new Error("Token GitHub manquant.");const res=await fetch(`https://api.github.com/repos/${s.owner}/${s.repo}/contents/${path}`,{...options,headers:{Authorization:`Bearer ${s.token}`,Accept:"application/vnd.github+json","Content-Type":"application/json",...(options.headers||{})}});const txt=await res.text();if(!res.ok)throw new Error(txt||res.statusText);return txt?JSON.parse(txt):{};}

function emptyItem(){return{image:"",photos:[],title:"",category:"creations",icon:"🎨",description:"",long_description:"",details:"",dimensions:"",duration:"",featured:false,draft:true,date:""};}
function normalizeItem(item){const d=item.description_section||{}, im=item.images_section||{}, inf=item.infos_section||{};const cat=item.category||d.category||"creations";return{image:item.image||im.image||"",photos:item.photos||im.photos||[],title:item.title||d.title||"",category:cat,icon:categoryIcon(cat),description:item.description||d.description||"",long_description:item.long_description||d.long_description||"",details:item.details||inf.details||"",dimensions:item.dimensions||inf.dimensions||"",duration:item.duration||inf.duration||"",featured:item.featured??inf.featured??false,draft:item.draft??false,date:item.date||inf.date||""};}
async function loadSiteData(){try{const live=await fetch("/content/realisations.json?ts="+Date.now()).then(r=>r.json());data.body=(live.body||[]).map(normalizeItem);}catch(e){data.body=[];} selected=data.body.length?0:-1; render();}

function syncIcon(){const ic=categoryIcon($("category")?.value||"creations");if($("icon"))$("icon").value=ic;if($("autoIcon"))$("autoIcon").textContent=ic;}
function saveForm(){if(selected<0||!$("form"))return;const it=data.body[selected];["image","title","description","long_description","details","dimensions","duration"].forEach(id=>{if($(id))it[id]=$(id).value.trim();});it.category=$("category")?.value||"creations";it.icon=categoryIcon(it.category);it.featured=!!$("featured")?.checked;it.draft=!!$("draft")?.checked;it.date=$("date")?.value||"";it.photos=$$(".photo-row").map(row=>({photo:row.querySelector(".photo-path")?.value.trim()||"",caption:row.querySelector(".photo-caption")?.value.trim()||""})).filter(p=>p.photo);}
function loadForm(){if(selected<0){if($("formTitle"))$("formTitle").textContent="Aucune réalisation";return;}const it=data.body[selected];if($("formTitle"))$("formTitle").textContent=it.title||"Nouvelle réalisation";["image","title","description","long_description","details","dimensions","duration"].forEach(id=>{if($(id))$(id).value=it[id]||"";});if($("category"))$("category").value=it.category||"creations";syncIcon();if($("featured"))$("featured").checked=!!it.featured;if($("draft"))$("draft").checked=!!it.draft;if($("date"))$("date").value=(it.date||"").slice(0,10);if($("mainPreview"))$("mainPreview").src=it.image||"/assets/logo.png";if($("photos"))$("photos").innerHTML="";(it.photos||[]).forEach(addPhotoRow);}
function addPhotoRow(photo={photo:"",caption:""}){if(!$("photos"))return;const row=document.createElement("div");row.className="photo-row";row.innerHTML=`<img src="${esc(photo.photo||'/assets/logo.png')}"><input class="photo-path" placeholder="/assets/uploads/photo.jpg" value="${esc(photo.photo||"")}"><input class="photo-caption" placeholder="Légende" value="${esc(photo.caption||"")}"><button type="button">⭐</button><button type="button">↑</button><button type="button">↓</button><button type="button">×</button>`;const b=row.querySelectorAll("button");row.querySelector("img").ondblclick=()=>openImageModal(row.querySelector("img").src);b[0].onclick=()=>{saveForm();const path=row.querySelector(".photo-path").value;const cur=$("image")?.value||"";if($("image"))$("image").value=path;row.querySelector(".photo-path").value=cur;if($("mainPreview"))$("mainPreview").src=path||"/assets/logo.png";saveForm();render();};b[1].onclick=()=>{if(row.previousElementSibling)$("photos").insertBefore(row,row.previousElementSibling);};b[2].onclick=()=>{if(row.nextElementSibling)$("photos").insertBefore(row.nextElementSibling,row);};b[3].onclick=()=>row.remove();$("photos").appendChild(row);}

function visibleByFilter(it){if(currentListFilter==="all")return true;if(currentListFilter==="active")return !it.draft;if(currentListFilter==="draft")return !!it.draft;if(currentListFilter==="featured")return !!it.featured&&!it.draft;return true;}
function renderList(){if(!$("list"))return;const q=($("searchList")?.value||"").toLowerCase();const rows=data.body.map((it,i)=>({it,i})).filter(x=>visibleByFilter(x.it)).filter(x=>!q||(x.it.title+" "+x.it.description+" "+x.it.category).toLowerCase().includes(q));$("list").innerHTML=rows.length?rows.map(({it,i})=>`<div class="item ${i===selected?'active':''} ${it.draft?'draft':''}" data-i="${i}"><img src="${it.image||'/assets/logo.png'}"><div><strong>${categoryIcon(it.category)} ${esc(it.title||'Nouvelle réalisation')}</strong><small><span class="catBadge">${categoryLabel(it.category)}</span> • ${(it.photos||[]).length+1} photo(s)${it.featured?' • À la une':''}${it.draft?' • Brouillon':''}</small></div></div>`).join(""):`<div class="emptyList">Aucune réalisation dans ce filtre.</div>`;$$(".item").forEach(el=>el.onclick=()=>{saveForm();selected=Number(el.dataset.i);render();});}
function renderPhotos(){const grid=$("photoGrid");if(!grid)return;const imgs=[];data.body.forEach(r=>{if(r.image)imgs.push(r.image);(r.photos||[]).forEach(p=>imgs.push(p.photo));});const q=($("librarySearch")?.value||"").toLowerCase();const unique=[...new Set(imgs)].filter(Boolean).filter(src=>src.toLowerCase().includes(q));grid.innerHTML=unique.map(src=>`<div class="libItem ${src===selectedLibraryImage?'selected':''}" data-src="${esc(src)}"><img src="${esc(src)}"><small>${esc(src.split('/').pop())}</small></div>`).join("");$$(".libItem").forEach(el=>{el.onclick=()=>{selectedLibraryImage=el.dataset.src;renderPhotos();};el.querySelector("img").ondblclick=()=>openImageModal(el.dataset.src);});}
function stats(){if($("countTotal"))$("countTotal").textContent=data.body.length;if($("countFeatured"))$("countFeatured").textContent=data.body.filter(x=>x.featured&&!x.draft).length;if($("countPhotos"))$("countPhotos").textContent=data.body.reduce((n,x)=>n+1+(x.photos||[]).length,0);if($("countDrafts"))$("countDrafts").textContent=data.body.filter(x=>x.draft).length;}
function render(){renderList();loadForm();renderPhotos();stats();}

function setFilter(f){currentListFilter=f;$$(".filterPill").forEach(b=>b.classList.toggle("active",b.dataset.filter===f));renderList();}
function newItem(){saveForm();data.body.push(emptyItem());selected=data.body.length-1;setFilter("draft");render();}
function duplicate(){if(selected<0)return;saveForm();const copy=JSON.parse(JSON.stringify(data.body[selected]));copy.title=(copy.title||"Réalisation")+" - copie";copy.draft=true;data.body.splice(selected+1,0,copy);selected++;setFilter("draft");render();}
function archiveSelected(){if(selected<0)return;data.body[selected].draft=true;setFilter("active");render();alert("Réalisation archivée. Elle ne sera plus affichée après publication.");}
function restoreSelected(){if(selected<0)return;data.body[selected].draft=false;setFilter("active");render();alert("Réalisation réactivée.");}
function del(){if(selected<0)return;if(!confirm("Supprimer définitivement cette réalisation ?"))return;data.body.splice(selected,1);selected=data.body.length?Math.max(0,selected-1):-1;render();}

function cleanData(){return{body:data.body.filter(x=>!x.draft).map(normalizeItem)};}
function toBase64Utf8(str){return btoa(unescape(encodeURIComponent(str)));}
async function publish(){try{saveForm();validateBeforePublish();$("publishBtn").disabled=true;$("publishBtn").textContent="Publication...";const path="content/realisations.json";const current=await gh(path);const content=toBase64Utf8(JSON.stringify(cleanData(),null,2));await gh(path,{method:"PUT",body:JSON.stringify({message:"Publication depuis le back-office V11",content,sha:current.sha,branch:settings().branch})});alert("Publication envoyée sur GitHub. Cloudflare va redéployer le site automatiquement.");}catch(e){alert("Erreur publication : "+e.message);}finally{$("publishBtn").disabled=false;$("publishBtn").textContent="🚀 Publier";}}
function validateBeforePublish(){for(const r of data.body){if(r.draft)continue;if(!r.title)throw new Error("Une réalisation publiée n'a pas de titre.");if(!r.image)throw new Error("La réalisation "+r.title+" n'a pas d'image principale.");}}
function fileToBase64(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(",")[1]);r.onerror=reject;r.readAsDataURL(file);});}
function safeName(name){return name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9.]+/g,"-").replace(/-+/g,"-");}
async function uploadFile(file){const filename=Date.now()+"-"+safeName(file.name);const path="assets/uploads/"+filename;const content=await fileToBase64(file);await gh(path,{method:"PUT",body:JSON.stringify({message:"Ajout image "+filename,content,branch:settings().branch})});return "/"+path;}
async function uploadMain(){try{const f=$("mainUpload")?.files[0];if(!f)return alert("Choisis une image.");const path=await uploadFile(f);$("image").value=path;$("mainPreview").src=path;saveForm();render();alert("Image envoyée.");}catch(e){alert("Erreur upload : "+e.message);}}
async function uploadExtra(){try{const files=[...($("extraUpload")?.files||[])];if(!files.length)return alert("Choisis une ou plusieurs images.");for(const f of files){const path=await uploadFile(f);addPhotoRow({photo:path,caption:""});}saveForm();render();alert("Photos envoyées.");}catch(e){alert("Erreur upload : "+e.message);}}
function setupDrop(id,inputId,callback){const dz=$(id), input=$(inputId);if(!dz||!input)return;["dragenter","dragover"].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.add("drag");}));["dragleave","drop"].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.remove("drag");}));dz.addEventListener("drop",e=>{input.files=e.dataTransfer.files;callback();});}
async function testGithub(){try{await gh("content/realisations.json");alert("Connexion GitHub OK.");}catch(e){alert("Connexion impossible : "+e.message);}}
function suggestText(){const t=$("title")?.value.trim()||"Cette réalisation";const cat=$("category")?.value||"creations";const map={impression3d:"Pièce réalisée en impression 3D, adaptée au besoin et préparée sur mesure.",reparations:"Diagnostic et remise en état selon la faisabilité de la réparation.",laser:"Personnalisation réalisée par gravure ou découpe laser.",decoupe:"Découpe laser réalisée sur mesure à partir du projet demandé.",creations:"Création personnalisée réalisée selon la demande."};if($("description")&&!$("description").value)$("description").value=map[cat];if($("long_description")&&!$("long_description").value)$("long_description").value=t+" : "+map[cat];}
function addSelectedToGallery(){if(!selectedLibraryImage)return alert("Sélectionne d'abord une image dans la bibliothèque.");addPhotoRow({photo:selectedLibraryImage,caption:""});saveForm();render();}
function useSelectedAsMain(){if(!selectedLibraryImage)return alert("Sélectionne d'abord une image dans la bibliothèque.");$("image").value=selectedLibraryImage;$("mainPreview").src=selectedLibraryImage;saveForm();render();}
function openImageModal(src){$("modalImage").src=src;$("imageModal").classList.add("open");}
function closeImageModal(){$("imageModal").classList.remove("open");}

document.addEventListener("DOMContentLoaded",()=>{
  document.addEventListener("click",e=>{
    const target=e.target.closest("[data-open]");
    if(target){showView(target.dataset.open);}
  });
  $$(".filterPill").forEach(b=>b.onclick=()=>{saveForm();setFilter(b.dataset.filter);});
  on("saveSettingsBtn","click",saveSettings);on("testGithubBtn","click",testGithub);on("clearTokenBtn","click",()=>{localStorage.removeItem("gh_token");loadSettings();});on("publishBtn","click",publish);
  on("newBtn","click",newItem);on("duplicateBtn","click",duplicate);on("archiveBtn","click",archiveSelected);on("restoreBtn","click",restoreSelected);on("deleteBtn","click",del);
  on("addPhotoBtn","click",()=>addPhotoRow());on("uploadMainBtn","click",uploadMain);on("uploadExtraBtn","click",uploadExtra);on("refreshLibraryBtn","click",renderPhotos);on("addSelectedToGalleryBtn","click",addSelectedToGallery);on("useAsMainBtn","click",useSelectedAsMain);on("suggestBtn","click",suggestText);
  on("image","input",()=>{$("mainPreview").src=$("image").value||"/assets/logo.png";});on("category","change",()=>{syncIcon();saveForm();renderList();});on("searchList","input",renderList);on("librarySearch","input",renderPhotos);on("closeModalBtn","click",closeImageModal);
  const form=$("form");if(form)form.onsubmit=e=>{e.preventDefault();saveForm();render();alert("Enregistré localement. Clique sur Publier pour envoyer sur GitHub.");};
  loadSettings();loadSiteData();setupDrop("mainDrop","mainUpload",uploadMain);setupDrop("extraDrop","extraUpload",uploadExtra);
});
