
let data={body:[]},selected=-1,selectedLibraryImage="",currentListFilter="active";
const $=id=>document.getElementById(id),qsa=s=>[...document.querySelectorAll(s)];
const IC={reparations:"🔧",impression3d:"🖨️",laser:"🔥",decoupe:"✂️",creations:"🎨"};
const LB={reparations:"Réparations",impression3d:"Impression 3D",laser:"Gravure laser",decoupe:"Découpe laser",creations:"Créations"};
function icon(c){return IC[c]||"🎨"} function label(c){return LB[c]||c||""}
function esc(s){return String(s).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function syncIcon(){let i=icon($("category")?.value||"creations"); if($("icon"))$("icon").value=i; if($("autoIcon"))$("autoIcon").textContent=i}
function emptyItem(){return{image:"",photos:[],title:"",category:"creations",icon:"🎨",description:"",long_description:"",details:"",dimensions:"",duration:"",featured:false,draft:true,date:""}}
function norm(it){let d=it.description_section||{},im=it.images_section||{},inf=it.infos_section||{},cat=it.category||d.category||"creations";return{image:it.image||im.image||"",photos:it.photos||im.photos||[],title:it.title||d.title||"",category:cat,icon:icon(cat),description:it.description||d.description||"",long_description:it.long_description||d.long_description||"",details:it.details||inf.details||"",dimensions:it.dimensions||inf.dimensions||"",duration:it.duration||inf.duration||"",featured:it.featured??inf.featured??false,draft:it.draft??false,date:it.date||inf.date||""}}
function settings(){return{owner:localStorage.gh_owner||"LuckyMcGyver",repo:localStorage.gh_repo||"lucky-reparations-creations",branch:localStorage.gh_branch||"main",token:localStorage.gh_token||""}}
function updateStatus(){let s=$("status"); if(!s)return; if(settings().token){s.textContent="Connecté à GitHub";s.classList.add("ok")}else{s.textContent="Non connecté à GitHub";s.classList.remove("ok")}}
function loadSettings(){let s=settings(); if($("repoOwner"))$("repoOwner").value=s.owner;if($("repoName"))$("repoName").value=s.repo;if($("repoBranch"))$("repoBranch").value=s.branch;if($("githubToken"))$("githubToken").value=s.token;updateStatus()}
function saveSettings(){localStorage.gh_owner=$("repoOwner").value.trim();localStorage.gh_repo=$("repoName").value.trim();localStorage.gh_branch=$("repoBranch").value.trim();localStorage.gh_token=$("githubToken").value.trim();updateStatus();alert("Paramètres enregistrés.")}
async function gh(path,opt={}){let s=settings();if(!s.token)throw Error("Token GitHub manquant.");let r=await fetch(`https://api.github.com/repos/${s.owner}/${s.repo}/contents/${path}`,{...opt,headers:{Authorization:`Bearer ${s.token}`,Accept:"application/vnd.github+json","Content-Type":"application/json",...(opt.headers||{})}});let t=await r.text();if(!r.ok)throw Error(t||r.statusText);return t?JSON.parse(t):{}}
async function loadSiteData(){try{let j=await fetch("/content/realisations.json?ts="+Date.now()).then(r=>r.json());data.body=(j.body||[]).map(norm)}catch(e){data.body=[]}selected=data.body.length?0:-1;render()}
function saveForm(){if(selected<0)return;let it=data.body[selected];["image","title","description","long_description","details","dimensions","duration"].forEach(id=>{if($(id))it[id]=$(id).value.trim()});if($("category"))it.category=$("category").value;it.icon=icon(it.category);if($("featured"))it.featured=$("featured").checked;if($("draft"))it.draft=$("draft").checked;if($("date"))it.date=$("date").value||"";it.photos=qsa(".photo-row").map(r=>({photo:r.querySelector(".photo-path")?.value.trim()||"",caption:r.querySelector(".photo-caption")?.value.trim()||""})).filter(p=>p.photo)}
function loadForm(){if(selected<0){if($("formTitle"))$("formTitle").textContent="Aucune réalisation";return}let it=data.body[selected];if($("formTitle"))$("formTitle").textContent=it.title||"Nouvelle réalisation";["image","title","description","long_description","details","dimensions","duration"].forEach(id=>{if($(id))$(id).value=it[id]||""});if($("category"))$("category").value=it.category||"creations";syncIcon();if($("featured"))$("featured").checked=!!it.featured;if($("draft"))$("draft").checked=!!it.draft;if($("date"))$("date").value=(it.date||"").slice(0,10);if($("mainPreview"))$("mainPreview").src=it.image||"/assets/logo.png";if($("photos")){$("photos").innerHTML="";(it.photos||[]).forEach(addPhotoRow)}}
function addPhotoRow(p={photo:"",caption:""}){let c=$("photos");if(!c)return;let r=document.createElement("div");r.className="photo-row";r.innerHTML=`<img src="${esc(p.photo||'/assets/logo.png')}" ondblclick="openImageModal(this.src)"><input class="photo-path" placeholder="/assets/uploads/photo.jpg" value="${esc(p.photo||"")}"><input class="photo-caption" placeholder="Légende" value="${esc(p.caption||"")}"><button type="button">⭐</button><button type="button">↑</button><button type="button">↓</button><button type="button">×</button>`;let b=r.querySelectorAll("button");b[0].onclick=()=>{let path=r.querySelector(".photo-path").value,cur=$("image").value;$("image").value=path;r.querySelector(".photo-path").value=cur;if($("mainPreview"))$("mainPreview").src=path||"/assets/logo.png"};b[1].onclick=()=>{if(r.previousElementSibling)c.insertBefore(r,r.previousElementSibling)};b[2].onclick=()=>{if(r.nextElementSibling)c.insertBefore(r.nextElementSibling,r)};b[3].onclick=()=>r.remove();c.appendChild(r)}
function visible(it){return currentListFilter==="all"||currentListFilter==="active"&&!it.draft||currentListFilter==="featured"&&it.featured&&!it.draft||(currentListFilter==="draft"||currentListFilter==="archived")&&it.draft}
function renderList(){let el=$("list");if(!el)return;let q=($("searchList")?.value||"").toLowerCase();let rows=data.body.map((it,i)=>({it,i})).filter(x=>visible(x.it)).filter(x=>!q||(x.it.title+" "+x.it.description+" "+x.it.category).toLowerCase().includes(q));el.innerHTML=rows.length?rows.map(({it,i})=>`<div class="item ${i===selected?'active':''} ${it.draft?'draft':''}" data-i="${i}"><img src="${it.image||'/assets/logo.png'}"><div><strong>${icon(it.category)} ${esc(it.title||'Nouvelle réalisation')}</strong><small><span class="catBadge">${label(it.category)}</span> • ${(it.photos||[]).length+1} photo(s)${it.featured?' • À la une':''}${it.draft?' • Brouillon/archivé':''}</small></div></div>`).join(""):'<div class="emptyList">Aucune réalisation dans ce filtre.</div>';qsa(".item").forEach(x=>x.onclick=()=>{saveForm();selected=+x.dataset.i;render()})}
function renderPhotos(){let g=$("photoGrid");if(!g)return;let imgs=[];data.body.forEach(r=>{if(r.image)imgs.push(r.image);(r.photos||[]).forEach(p=>imgs.push(p.photo))});let q=($("librarySearch")?.value||"").toLowerCase();g.innerHTML=[...new Set(imgs)].filter(Boolean).filter(s=>s.toLowerCase().includes(q)).map(src=>`<div class="libItem ${src===selectedLibraryImage?'selected':''}" data-src="${esc(src)}"><img src="${esc(src)}" ondblclick="openImageModal(this.src)"><small>${esc(src.split('/').pop())}</small></div>`).join("");qsa(".libItem").forEach(x=>x.onclick=()=>{selectedLibraryImage=x.dataset.src;renderPhotos()})}
function stats(){if($("countTotal"))$("countTotal").textContent=data.body.length;if($("countFeatured"))$("countFeatured").textContent=data.body.filter(x=>x.featured&&!x.draft).length;if($("countPhotos"))$("countPhotos").textContent=data.body.reduce((n,x)=>n+1+(x.photos||[]).length,0);if($("countDrafts"))$("countDrafts").textContent=data.body.filter(x=>x.draft).length}
function render(){renderList();loadForm();renderPhotos();stats()}
function setFilter(f){currentListFilter=f;qsa(".filterPill").forEach(b=>b.classList.toggle("active",b.dataset.filter===f))}
function newItem(){saveForm();data.body.push(emptyItem());selected=data.body.length-1;setFilter("draft");render()}
function duplicate(){if(selected<0)return;saveForm();let c=JSON.parse(JSON.stringify(data.body[selected]));c.title=(c.title||"Réalisation")+" - copie";c.draft=true;data.body.splice(selected+1,0,c);selected++;setFilter("draft");render()}
function archiveSelected(){if(selected<0)return;data.body[selected].draft=true;setFilter("active");render();alert("Réalisation archivée.")}
function restoreSelected(){if(selected<0)return;data.body[selected].draft=false;setFilter("active");render();alert("Réalisation réactivée.")}
function del(){if(selected<0)return;if(confirm("Supprimer définitivement ?")){data.body.splice(selected,1);selected=data.body.length?Math.max(0,selected-1):-1;render()}}
function cleanData(){return{body:data.body.filter(x=>!x.draft).map(norm)}}
function b64(s){return btoa(unescape(encodeURIComponent(s)))}
async function publish(){try{saveForm();for(let r of data.body){if(!r.draft&&(!r.title||!r.image))throw Error("Une réalisation active n'a pas de titre ou d'image.");}$("publishBtn").disabled=true;$("publishBtn").textContent="Publication...";let cur=await gh("content/realisations.json");await gh("content/realisations.json",{method:"PUT",body:JSON.stringify({message:"Publication depuis le back-office V10.5",content:b64(JSON.stringify(cleanData(),null,2)),sha:cur.sha,branch:settings().branch})});alert("Publication envoyée sur GitHub. Cloudflare va redéployer le site automatiquement.")}catch(e){alert("Erreur publication : "+e.message)}finally{if($("publishBtn")){$("publishBtn").disabled=false;$("publishBtn").textContent="🚀 Publier"}}}
function fileToBase64(f){return new Promise((res,rej)=>{let r=new FileReader();r.onload=()=>res(String(r.result).split(",")[1]);r.onerror=rej;r.readAsDataURL(f)})}
function safeName(n){return n.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9.]+/g,"-").replace(/-+/g,"-")}
async function uploadFile(f){let name=Date.now()+"-"+safeName(f.name),path="assets/uploads/"+name;await gh(path,{method:"PUT",body:JSON.stringify({message:"Ajout image "+name,content:await fileToBase64(f),branch:settings().branch})});return "/"+path}
async function uploadMain(){try{let f=$("mainUpload")?.files[0];if(!f)return alert("Choisis une image.");let p=await uploadFile(f);$("image").value=p;if($("mainPreview"))$("mainPreview").src=p;saveForm();render();alert("Image envoyée.")}catch(e){alert("Erreur upload : "+e.message)}}
async function uploadExtra(){try{let fs=[...($("extraUpload")?.files||[])];if(!fs.length)return alert("Choisis une image.");for(let f of fs)addPhotoRow({photo:await uploadFile(f),caption:""});saveForm();render();alert("Photos envoyées.")}catch(e){alert("Erreur upload : "+e.message)}}
function setupDrop(id,inputId,cb){let d=$(id),i=$(inputId);if(!d||!i)return;["dragenter","dragover"].forEach(ev=>d.addEventListener(ev,e=>{e.preventDefault();d.classList.add("drag")}));["dragleave","drop"].forEach(ev=>d.addEventListener(ev,e=>{e.preventDefault();d.classList.remove("drag")}));d.addEventListener("drop",e=>{i.files=e.dataTransfer.files;cb()})}
async function testGithub(){try{await gh("content/realisations.json");alert("Connexion GitHub OK.")}catch(e){alert("Connexion impossible : "+e.message)}}
function suggestText(){let t=$("title")?.value.trim()||"Cette réalisation",cat=$("category")?.value||"creations",m={impression3d:"Pièce réalisée en impression 3D, adaptée au besoin et préparée sur mesure.",reparations:"Diagnostic et remise en état selon la faisabilité de la réparation.",laser:"Personnalisation réalisée par gravure ou découpe laser.",decoupe:"Découpe laser réalisée sur mesure à partir du projet demandé.",creations:"Création personnalisée réalisée selon la demande."};if($("description")&&!$("description").value)$("description").value=m[cat];if($("long_description")&&!$("long_description").value)$("long_description").value=t+" : "+m[cat]}
function addSelectedToGallery(){if(!selectedLibraryImage)return alert("Sélectionne une image.");addPhotoRow({photo:selectedLibraryImage,caption:""});saveForm();render()}
function useSelectedAsMain(){if(!selectedLibraryImage)return alert("Sélectionne une image.");$("image").value=selectedLibraryImage;if($("mainPreview"))$("mainPreview").src=selectedLibraryImage;saveForm();render()}
function openImageModal(src){if($("imageModal")){$("modalImage").src=src;$("imageModal").classList.add("open")}}
function closeImageModal(){if($("imageModal"))$("imageModal").classList.remove("open")}
function showView(id){qsa(".tab").forEach(x=>x.classList.remove("active"));qsa(".view").forEach(x=>x.classList.remove("active"));document.querySelector(`[data-view="${id}"]`)?.classList.add("active");$(id)?.classList.add("active")}
document.addEventListener("DOMContentLoaded",()=>{qsa(".tab").forEach(b=>b.onclick=()=>showView(b.dataset.view));qsa(".filterPill").forEach(b=>b.onclick=()=>{saveForm();setFilter(b.dataset.filter);renderList()});[["settingsBtn",()=>showView("settings")],["saveSettingsBtn",saveSettings],["testGithubBtn",testGithub],["clearTokenBtn",()=>{localStorage.removeItem("gh_token");loadSettings()}],["publishBtn",publish],["newBtn",newItem],["duplicateBtn",duplicate],["archiveBtn",archiveSelected],["restoreBtn",restoreSelected],["deleteBtn",del],["addPhotoBtn",()=>addPhotoRow()],["uploadMainBtn",uploadMain],["uploadExtraBtn",uploadExtra],["refreshLibraryBtn",renderPhotos],["addSelectedToGalleryBtn",addSelectedToGallery],["useAsMainBtn",useSelectedAsMain],["suggestBtn",suggestText]].forEach(([id,fn])=>{if($(id))$(id).onclick=fn});if($("form"))$("form").onsubmit=e=>{e.preventDefault();saveForm();render();alert("Enregistré localement. Clique sur Publier pour envoyer sur GitHub.")};if($("image"))$("image").oninput=()=>{if($("mainPreview"))$("mainPreview").src=$("image").value||"/assets/logo.png"};if($("category"))$("category").onchange=()=>{syncIcon();saveForm();renderList()};if($("searchList"))$("searchList").oninput=renderList;if($("librarySearch"))$("librarySearch").oninput=renderPhotos;loadSettings();loadSiteData();setupDrop("mainDrop","mainUpload",uploadMain);setupDrop("extraDrop","extraUpload",uploadExtra)});
